\input texinfo
@ignore
\internalpagesizes{46\baselineskip}{6in}{-.25in}{-.25in}{\bindingoffset}{36pt}%
@end ignore
@c %**start of header
@include version.texi

@setfilename gnu-pw-mgr.info
@settitle @value{TITLE}
@dircategory Miscellenaeous tools
@direntry
* gnu-pw-mgr: (gnu-pw-mgr).     Invoking gnu-pw-mgr
@end direntry
@setchapternewpage off
@syncodeindex pg cp
@finalout
@c %**end of header

@copying
This manual is for gnu-pw-mgr version @value{VERSION},
updated @value{UPDATED-MONTH}

Copyright @copyright{} 2013 by Bruce Korb.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts and no Back-Cover Texts.
@end quotation
@end copying

@titlepage
@title @value{TITLE}
@subtitle For version @value{VERSION}, @value{UPDATED-MONTH}
@author Bruce Korb
@author @email{bkorb@@gnu.org}

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top, Introduction, (dir), (dir)
@top @value{TITLE}
@end ifnottex

This program is designed to make it easy to reconstruct difficult
passwords when they are needed while limiting the risk of attack.
The user of this program inputs a self-defined transformation of a web site
URL and obtains the password and user name hint for that web site.
You must, however, be able to remember this password id, or the password
is lost forever.

The Wikipedia has an 
@uref{https://en.wikipedia.org/wiki/Password_strength,excellent article}
on passwords in general and there is a
@uref{http://crypto.stanford.edu/PwdHash/pwdhash.pdf,paper published at Stanford}*
that describes a browser plug-in that is substantially similar to this program.

@menu
* Introduction::                Introduction to password management
* gnu-pw-mgr Invocation::       Invoking gnu-pw-mgr
* warning warning::             Warnings
* GNU FDL::                     GNU Free Documentation License
@end menu

* Blake Ross; Collin Jackson, Nicholas Miyake, Dan Boneh and John C. Mitchell
  (2005). "Stronger Password Authentication Using Browser
  Extensions". Proceedings of the 14th Usenix Security
  Symposium. USENIX. pp. 17–32

@include intro.texi

@include invoke-gnu-pw-mgr.texi

@include warnings.texi

@node GNU FDL
@appendix GNU Free Documentation License

@include fdl.texi

@bye

@c Local variables:
@c texinfo-column-for-description: 32
@c End:
